### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by mohebifar** [siamakmokhtari/webpack-react-babel-boilerplate#1]
Happy to see yet another react boilerplate. However, I don't see any advantages over [existing boilerplates](https://github.com/enaqx/awesome-react#boilerplates). It does not represent a new approach, architecture, pattern, etc. Apart from this, there are some other issues such as using two different linters (jshint, eslint).

Hope to see something new in this repo.

**Comment by siamak** [comment]
Thanks Mohammad, I build new things in this repo soon ;)

**Comment by siamak** [comment]
I had released Node_ENV in this version ;)
